import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

import RootComponent from "./RootComponent";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} `}
      >
        <RootComponent>{children}</RootComponent>
      </body>
    </html>
  );
}
