export const Permission = Object.freeze({
    // Platform
    VIEW_ALL_ORGANIZERS: "VIEW_ALL_ORGANIZERS",
    VIEW_ALL_EVENTS: "VIEW_ALL_EVENTS",
    APPROVE_EVENT: "APPROVE_EVENT",
    VIEW_REPORTS: "VIEW_REPORTS",

    CREATE_ORGANIZER: "CREATE_ORGANIZER",
    MANAGE_ORGANIZER: "MANAGE_ORGANIZER",

    // Organizer
    CREATE_EVENT: "CREATE_EVENT",
    MANAGE_EVENT: "MANAGE_EVENT",

    // Booking
    CREATE_BOOKING: "CREATE_BOOKING",

    // Scanner
    SCAN_TICKET: "SCAN_TICKET",
  });
